This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./Memoria.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Memoria.acn....done (121 entries accepted, 0 rejected).
Sorting entries....done (848 comparisons).
Generating output file Memoria.acr....done (68 lines written, 0 warnings).
Output written in Memoria.acr.
Transcript written in Memoria.alg.
